### ISSUE TITLE
[FR]: Support custom color when drawing.

### ISSUE THREAD

**Issue by YIRU69** [ocapraro/obsidian-math-plus#1]
Pleasure support custom colore when I drawing.
I have a problem when I drawing on light theme. I can't see because the line is white.
And maybe it could open excalidraw file above the math block.

**Comment by ocapraro** [comment]
Whoops, I kind of forgot about light mode 😅 . It should be fixed now in v0.1.2. I'm not exactly sure what you mean by open above the math block, could you be more specific?

**Comment by YIRU69** [comment]
> Whoops, I kind of forgot about light mode 😅 . It should be fixed now in v0.1.2. I'm not exactly sure what you mean by open above the math block, could you be more specific?

I mean that we can use pen text or other in custom color. I want the plugin can support custom color what I want to choose. And I want it could open with excalidraw.

**Comment by ocapraro** [comment]
So something like this?

![Screen Shot 2022-04-14 at 11 49 08 AM](https://user-images.githubusercontent.com/25327166/163457827-62aae8e0-5991-4a4a-aa07-46866e5e3c76.png)

**Comment by YIRU69** [comment]
> So something like this?
> 
> ![Screen Shot 2022-04-14 at 11 49 08 AM](https://user-images.githubusercontent.com/25327166/163457827-62aae8e0-5991-4a4a-aa07-46866e5e3c76.png)

Yeah, that's so cool.

**Comment by ocapraro** [comment]
It's been added to the most recent version!
