### ISSUE TITLE
Unable to handle \right) and \left(

### ISSUE THREAD

**Issue by eliazar-sll** [ocapraro/obsidian-math-plus#12]
There seems to be a bug when handling `\right)` and `\left(`

![image](https://user-images.githubusercontent.com/75558018/213596002-675d6d70-b467-4b9b-87b1-94003ad32511.png)

Although it works fine with `|`, (`\right|` and `\left|`)

![image](https://user-images.githubusercontent.com/75558018/213595911-4e186f0d-06f8-4d59-bfac-419e283609d5.png)

**Comment by ocapraro** [comment]
Good catch, I'll add this in by default in the next version, but for a quick fix, you can add this to the top of your shortcuts array.
```
    {
        "op":"\left{(",
        "format":"{("
    },
    {
        "op":"\right)",
        "format":")"
    },
```

**Comment by gusdleon** [comment]
Sorry I finded this issue searching for answers about the same problem
after adding this to the shortcuts array
> 
> ```
>     {
>         "op":"\left{(",
>         "format":"{("
>     },
>     {
>         "op":"\right)",
>         "format":")"
>     },
> ```

It solves the error but did not format the round brackets () as it does with the vertical bars |

the result of..

```
F = G ( \frac{m_1 m_2}{r^2} )
F = G \left( \frac{m_1 m_2}{r^2} \right)

F = G | \frac{m_1 m_2}{r^2} |
F = G \left| \frac{m_1 m_2}{r^2} \right|
```

is
![image](https://user-images.githubusercontent.com/3170940/215416591-74799091-496e-478d-b35e-d49c80a3a55a.png)

Maybe following the format of [Overleaf](https://www.overleaf.com/learn/latex/Brackets_and_Parentheses), helps with this.

**Comment by ocapraro** [comment]
Oh, I didn't realize `\left \right` dynamically resized.
Try these instead of the previous shortcuts:

```
    {
        "op":"\left{(",
        "format":"{\left("
    },
    {
        "op":"\right)",
        "format":"\right)"
    },
```

Let me know if this helps!

**Comment by gusdleon** [comment]
> Let me know if this helps!

I'm so sorry hahaha :( 
yep, it works now!
thank you!!, thank you so much.
