### ISSUE TITLE
Conflict with Numerals Plugin

### ISSUE THREAD

**Issue by harriswr** [ocapraro/obsidian-math-plus#14]
May be a bit outside of the scope of this plugin. I have another plugin called Numerals that acts as a calculator within the notes. It also uses the ```math``` block, so there is a conflict with the two where it either chooses Excalidraw or the Numerals mathblock depending on the order the Plugins were installed. Is there an easy way to change the type of block this plugin works for? I had tried editing the "registerMarkdownCodeBlockProcessor" in the .js file, but this led to "\int_{#1}^{#2}" to render an integral being replaced with "\in t_{#1}" which was unintended.

**Comment by duckfromdiscord** [comment]
This isn't a conflict, it's happening to me too. This needs to be fixed ASAP.


![image](https://github.com/ocapraro/obsidian-math-plus/assets/113956421/2c822a27-ae60-45f6-a69e-d832aadf00c9)

![image](https://github.com/ocapraro/obsidian-math-plus/assets/113956421/1ee9ef03-0ad5-4f16-849a-8d98a8282039)

**Comment by ocapraro** [comment]
This should be fixed in the latest release.
