### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by AlekseyOoo** [ocapraro/obsidian-math-plus#17]
Hello, I apologize for my English, I'm not very good at GIthub yet, please tell me where I can find all possible combinations for mathematical symbols

**Comment by ocapraro** [comment]
I'm not sure I fully understand. If you mean the mathematical symbols for LaTex, which is what this program uses, you can find those here:
https://www.cmor-faculty.rice.edu/~heinken/latex/symbols.pdf

Also this is a great resource for finding the code for symbols if you are still having trouble finding them:
https://detexify.kirelabs.org/classify.html

**Comment by ocapraro** [comment]
Stale
