### ISSUE TITLE
Math+ causes Excalidraw to stop working.

### ISSUE THREAD

**Issue by codecnotsupported** [ocapraro/obsidian-math-plus#2]
Related: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/605

https://user-images.githubusercontent.com/2294209/168047066-2648d499-6e43-4ac1-a38f-633a502e91c2.mp4

Notable that all the affected users were Linux users.

**Comment by ocapraro** [comment]
Thanks for letting me know! Looks like it was just bad CSS on my part, should be fixed in the newest release.
