### ISSUE TITLE
Bound integrals entirely broken

### ISSUE THREAD

**Issue by duckfromdiscord** [ocapraro/obsidian-math-plus#21]
I cannot do integrals with bounds in Obsidian Math Plus. 
`\int_{a}^{b}` changes to `\in t_{a}^{b}`.

**Comment by arrow501** [comment]
Unfortunately I have the same issue and I didn't find a workaround.

**Comment by ocapraro** [comment]
Thanks for your patience, this should be fixed in the latest release!
