### ISSUE TITLE
does not install on latest builds

### ISSUE THREAD

**Issue by lwb52** [ocapraro/obsidian-math-plus#23]
most recent Obsidian, on latest OSX (PowerBook M3 64GB) and iOS (iPadPro M2), but plugin failed to install when tried just a few minutes ago (Jan.24.`24, 11:15 PM US-Pacific)…
no report other than "Failed to install plugin…" on both machines

**Comment by AFellowEsin** [comment]
Same here. Must be a compatibility issue.

**Comment by ocapraro** [comment]
Should be fixed now, thank you for your patience.

**Comment by FellowEsin** [comment]
Thanks!

**Comment by lwb52** [comment]
👍🏻👍🏻🙏🏻

**Comment by LiamTheNinja5** [comment]
I am having this same issue on Linux mint 21.3 EDGE with the error "Failed to install plugin…"
