### ISSUE TITLE
Math+ causes Excalidraw UI to change

### ISSUE THREAD

**Issue by Tank159** [ocapraro/obsidian-math-plus#3]
Whenever the Plugin is activated, the Excalidraw toolbar at the bottom of the screen gets stretched out across the entire screen.
This unfortunately blocks most of the canvas.
Deactivating Math+ and restarting Obsidian brings back the normal toolbar.
Otherwise this plugin is absolutely amazing, thank you very very much.

Obsidian:  v0.15.9
Excalidraw: v1.78
Math+: v0.3.0

https://user-images.githubusercontent.com/46480101/181916162-14d51986-3b37-45bf-88be-00ea5bc882ca.mp4

**Comment by ocapraro** [comment]
Thanks for letting me know! This should be fixed in the latest version.
