### ISSUE TITLE
\oint is not rendered in the drawing

### ISSUE THREAD

**Issue by blacklightpy** [ocapraro/obsidian-math-plus#5]
`\oint` does not come in LaTeX by default, and has to be added using external packages. But Obsidian can render the symbol by default, and this plugin cannot.

According to this [page](https://www.physicsread.com/latex-close-integral/), the package required for this symbol can be either of `esint` or `wasysym`.

**Comment by ocapraro** [comment]
Could you include a screenshot, `\oint` looks like it renders for me.

<img width="932" alt="Screen Shot 2022-09-09 at 10 17 45 AM" src="https://user-images.githubusercontent.com/25327166/189371329-0db0768d-6b06-40cc-93d0-b5e348686a82.png">
