### ISSUE TITLE
Why no mobile support?

### ISSUE THREAD

**Issue by tajetaje** [ocapraro/obsidian-math-plus#6]
If it's just a formatting think I'd just throw a disclaimer in the readme and enable it. As an iPad user having this kind of functionality on my tablet would be awesome. Regardless of that, this is an amazing plugin, thanks for making it!

**Comment by ocapraro** [comment]
Thanks for letting me know! It should be working on mobile now. I hadn't enabled it before, because I don't have a great way to test it reliably, so it may not work as well as the desktop version. Please let me know if there are any issues with it.

**Comment by tajetaje** [comment]
seems to work well enough for me at least

**Comment by drPilman** [comment]
Hello! It seems the plugin has stopped working on mobile devices. at least in my Obsidian version 1.4.16(114), the math block simply disappears completely when the plugin is turned on, in any modes
