### ISSUE TITLE
Excalidraw "Keep selected tool active after drawing" icon not shown

### ISSUE THREAD

**Issue by FireIsGood** [ocapraro/obsidian-math-plus#8]
Excalidraw has a feature that allows you to lock the current tool to be active and you can still do it here with the key bind `q`, however it is not shown in the UI

Current implementation:

![image](https://user-images.githubusercontent.com/109556932/207239905-058d4bfa-97d0-47f4-a6e0-4b7d18de6ccc.png)

This makes it hard to tell when a tool is locked and lacks the GUI button.

A possible fix could make it look like:

![image](https://user-images.githubusercontent.com/109556932/207240046-fc42a9d5-ad01-441d-9e4d-5bc61a030f40.png)

**Comment by ocapraro** [comment]
Thank you for pointing this out, I completely forgot about that feature. This should be added in the next version.

**Comment by ocapraro** [comment]
[Done](https://github.com/ocapraro/obsidian-math-plus/releases/tag/0.5.0), thank you for helping to improve the plugin!
