### ISSUE TITLE
Add setting to change saved directory of drawings

### ISSUE THREAD

**Issue by FireIsGood** [ocapraro/obsidian-math-plus#9]
Currently the drawings are saved in the plugin's folder. This might be an issue for users backing up just the contents of their vault as the svg drawings would be paired with the configuration files. A fix would be adding a field in settings to allow users to designate a folder within the vault to save the images to.

A rough example of what it might look like

![mockup](https://user-images.githubusercontent.com/109556932/207241068-29cb56c4-cb87-435b-8c6b-baa66834cf27.jpg)

**Comment by ocapraro** [comment]
This seems like a great addition, thank you for pointing it out. It will be implemented within the next couple of versions.

**Comment by ocapraro** [comment]
[Should be working now](https://github.com/ocapraro/obsidian-math-plus/releases/tag/0.5.1). Thanks for the suggestions!
